### PR TITLE
Implement the shared subworkflows

### PR DESCRIPTION
**Pull request by muffato**
( https://jira.sanger.ac.uk/browse/TOLIT-727 )

A lot of the commits here are about polishing the subworkflows, which led to https://github.com/sanger-tol/nf-core-pipeline/pull/16 . In the end, this PR is mostly about making the pipeline use the shared sub-workflows, which means a lot of files moved / changed.

There is still enough make a version 1.1 release as:

- there was a bug with the tabix indexing of the bed files
- need to do csi indexes as well
- name the Fasta files .fa
- I've decided to reinstate the sample-sheet functionality. To make it portable while still matching our directory structure, the output paths in it are made relative to `--outdir`

Note: I have put all the sanger-tol/nf-core-pipeline into their own directories (not `local/`), anticipating how subworkflow import will work, especially as those files are exact copies from the other repo. I've also found the option in `.gitattributes` to  hide those files by default in the PR view.

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/insdcdownload/tree/master/.github/CONTRIBUTING.md)
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by muffato** [comment]
Hi @priyanka-surana . I want to open two other pull-requests for two more pipelines and make sure everything is consistent in terms of naming etc, before making this PR final. But in the meantime, this PR is still ready for review

**Review by priyanka-surana — COMMENTED** [review]
Looks good 😄 Merges already approved changes in `nf-core-pipeline`. I will wait for the other two PR before officially approving and merging.

**Comment by muffato** [comment]
This is now complete. I've aligned the various files with the other pipelines as much as I could.
In terms of functionality, very little has changed here. It's mostly code refactoring

**Review by priyanka-surana — APPROVED** [review]
I don't understand the naming/location of `sanger-tol/nf-core-pipeline/repeats_bed.nf`. Why is this not under `local` or `sanger-tol/nf-core-modules`?

Otherwise, it looks good to me.

**Comment by muffato** [comment]
> I don't understand the naming/location of `sanger-tol/nf-core-pipeline/repeats_bed.nf`. Why is this not under `local` or `sanger-tol/nf-core-modules`?

I made that structure up ! I wanted to distinguish modules that have been created specifically for this pipeline (`local`) from the ones created for our shared subworkflows (`sanger-tol/nf-core-pipeline`) from the ones shared in nf-core (`nf-core/modules`).

For the actual 1.1 release of this pipeline, I could perhaps delay it to next sprint, and 1) reorganise the modules and subworkflows according to the new nf-core standard that's coming, and 2) upgrade to the 2.6 template ?

**Comment by priyanka-surana** [comment]
I think it is okay to release and then once things are more stable with nf-core/tools, you can implement a TEMPLATE change and release a new version.

**Pull request merged**
